
package Vista;
import Modelo.*;
import Datos.*;
import javax.swing.JOptionPane;

public class GUIMenuPrincipal extends javax.swing.JFrame {
    private Empleado usuarioLogeado; //Para saber que usuario entro
    private GestionEmpleados empleados;
    private GestionReservasEstadias reservas;
    private GestionHabitaciones habitaciones;
    private GestionHuespedes huespedes;
    private GestionServicios servicios;
    private GestionConsumos consumos;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIMenuPrincipal.class.getName());

    
    public GUIMenuPrincipal(Empleado usuario, GestionReservasEstadias gre, GestionEmpleados ge,GestionHabitaciones gh, GestionHuespedes ghu, GestionServicios gs, GestionConsumos gc) {
        initComponents();
        
        // Guardar las referencias en los atributos de esta clase
        this.usuarioLogeado = usuario;
        this.reservas = gre;
        this.empleados = ge;
        this.habitaciones = gh;
        this.huespedes = ghu;
        this.servicios = gs;
        this.consumos = gc;
        
        // título
        this.setTitle("Menu Principal - Usuario: " + usuario.getNombres() + "(" + usuario.obtenerRol() + ")");
    }
    
    public GUIMenuPrincipal() {
        initComponents();
        if (this.empleados == null){
            System.out.println("entrando por constructor vacio: Creando datos de emergencia ...");
            //1. inicializamos el arreglo
            this.empleados = new GestionEmpleados(0);
            //admn por defecto
            Empleado admin = new Administrador("999", "Admin", "Emergencia", "admin", "123");
            this.empleados.crear(admin);
            
            // 3. Asignamos el usuario logueado para que no de error el título
            this.usuarioLogeado = admin;
            
            // (Opcional) Inicializa los otros gestores en null o vacíos si los necesitas
            // this.habitaciones = new GestionHabitaciones(10);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGestEmpl = new javax.swing.JToggleButton();
        btnGestHabPrec = new javax.swing.JToggleButton();
        btnGestServAdi = new javax.swing.JToggleButton();
        btnRepIngre = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnGestEmpl.setText("1. Gestion Empleados");
        btnGestEmpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestEmplActionPerformed(evt);
            }
        });

        btnGestHabPrec.setText("2. Gestion De Habitaciones Y Precios");
        btnGestHabPrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestHabPrecActionPerformed(evt);
            }
        });

        btnGestServAdi.setText("3. Gestion de Servicios Adicionales");
        btnGestServAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestServAdiActionPerformed(evt);
            }
        });

        btnRepIngre.setText("4. Reportes de Ingresos");
        btnRepIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepIngreActionPerformed(evt);
            }
        });

        jLabel1.setText("Menu Principal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGestServAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(btnGestEmpl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGestHabPrec, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(btnRepIngre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestHabPrec, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGestServAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(btnRepIngre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestEmplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestEmplActionPerformed
        // TODO add your handling code here:
        // verificacion de tener todos los datos
        if (this.empleados != null) {
            GUIGestionEmpleados gui = new GUIGestionEmpleados(this.empleados);
            gui.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Error: Datos de Empleados no cargados.");
        }
    }//GEN-LAST:event_btnGestEmplActionPerformed

    private void btnGestHabPrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestHabPrecActionPerformed
        // TODO add your handling code here:
        if (this.habitaciones != null) {
            // Creamos la ventana de habitaciones y le pasamos los datos
            GUIGestionHabitaciones guiHab = new GUIGestionHabitaciones(this.habitaciones);
            guiHab.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Error: Datos de Habitaciones no cargados.");
        }
    }//GEN-LAST:event_btnGestHabPrecActionPerformed

    private void btnGestServAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestServAdiActionPerformed
        // TODO add your handling code here:
        // Verificamos que el gestor de servicios exista
        if (this.servicios != null) {
            // 1. Creamos la ventana y le pasamos los datos (this.servicios)
            GUIGestionServicios ventanaServ = new GUIGestionServicios(this.servicios);
            
            // 2. Centramos la ventana
            ventanaServ.setLocationRelativeTo(null);
            
            // 3. La hacemos visible
            ventanaServ.setVisible(true);
            
        } else {
            // Si por alguna razón es null, mostramos error
            JOptionPane.showMessageDialog(this, "Error: El módulo de servicios no se ha cargado correctamente.");
        }
    }//GEN-LAST:event_btnGestServAdiActionPerformed

    private void btnRepIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepIngreActionPerformed
        // TODO add your handling code here:
        // Para reportes, usualmente necesitas las Reservas y los Consumos
        if (this.reservas != null && this.consumos != null) {
            GUIReporteIngresos ventanaReporte = new GUIReporteIngresos(this.reservas);
            ventanaReporte.setVisible(true);
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: El gestor de reservas no está inicializado.");
        }
    }//GEN-LAST:event_btnRepIngreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnGestEmpl;
    private javax.swing.JToggleButton btnGestHabPrec;
    private javax.swing.JToggleButton btnGestServAdi;
    private javax.swing.JToggleButton btnRepIngre;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
